apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
spec:
  ports:
  - name: vproapp-service-port
    port: 80
    targetPort: vproapp-port
    protocol: TCP
  type: LoadBalancer
  selector:
    app: vproapp
