apiVersion: v1
kind: Service
metadata:
  name: vprocache01 # Service name to contact it
spec:
  selector:
    app: vpromc
  ports:
  - name: vpromc-service-port
    port: 11211
    targetPort: vpromc-port
    protocol: TCP
  type: ClusterIP
